---
# tasks file for gpu_install
- name: Fail if unsupported vendor
  ansible.builtin.fail:
    msg: "Unsupported vendor {{ vendor }}"
  when: (gpu_install_vendor | lower) not in ['nvidia', 'amd']

- name: Include correct installation tasks
  ansible.builtin.include_tasks:
    file: "{{ gpu_install_vendor }}/main.yml"
