---
- name: Fail on unsupported distribution
  ansible.builtin.fail:
    msg: "Unsupported distribution {{ ansible_distribution }}"
  when: (ansible_distribution | lower) not in ["redhat", "fedora"]

- name: Prepare system facts
  ansible.builtin.include_tasks:
    file: "{{ vendor }}/pre_download/{{ ansible_distribution | lower }}.yml"

- name: Configure System
  ansible.builtin.include_tasks:
    file: "{{ vendor }}/install/{{ ansible_distribution | lower }}.yml"
