- name: Fail on unsupported archs
  ansible.builtin.fail:
    msg: "Unsupported arch for Amazon Linux {{ ansible_architecture }}"
  when: ansible_architecture != "x86_64"

- name: Set Download URL
  ansible.builtin.set_fact:
    download_url: "{{ lookup('ansible.builtin.template', 'nvidia/driver_url.j2', template_vars={'distro': 'amzn', 'extension': 'rpm'}) }}"
