- name: Fail on unsupported archs
  ansible.builtin.fail:
    msg: "Unsupported arch for Amazon Linux {{ ansible_architecture }}"
  when: ansible_architecture != "x86_64"

- name: Set Download URL
  ansible.builtin.set_fact:
    download_url: "{{ driver_base_url.nvidia }}/{{ driver_version }}/nvidia-driver-local-repo-amzn{{ ansible_distribution_major_version }}-{{ driver_version }}-1.0-1.{{ ansible_architecture }}.rpm"
