---
- name: Set RHEL-based URL
  ansible.builtin.set_fact:
    download_url: "{{ driver_base_url.nvidia }}/{{ driver_version }}/nvidia-driver-local-repo-rhel{{ ansible_distribution_major_version }}-{{ driver_version }}-1.0-1.{{ ansible_architecture }}.rpm"