---
- name: Install required packages/repos
  ansible.builtin.dnf:
    pkg:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
      - kernel-devel-{{ ansible_kernel }}
      - kernel-headers-{{ ansible_kernel }}
      - kernel-devel-matched-{{ ansible_kernel }}
      - python3-setuptools
      - python3-wheel
    state: present
  when: not gpu_install_dry_run

- name: Install AMD repo
  ansible.builtin.dnf:
    pkg:
      - "{{ download_url }}"
    state: present
    disable_gpg_check: true
  when: not gpu_install_dry_run

- name: Install AMD drivers
  ansible.builtin.dnf:
    pkg:
      - amdgpu-dkms
      - rocm
    state: present
  notify:
    - Reboot system
  when: not gpu_install_dry_run
