---
- name: Install GPU driver repository
  ansible.builtin.dnf:
    pkg:
      - "{{ download_url }}"
    state: present
    disable_gpg_check: true
  when: not dry_run

- name: Import EPEL RPM GPG Key
  ansible.builtin.rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
  when: not dry_run

- name: Install required packages/repos
  ansible.builtin.dnf:
    pkg:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
      - kernel-devel-{{ ansible_kernel }}
      - kernel-headers-{{ ansible_kernel }}
    state: present
  when: not dry_run

- name: Install Nvidia drivers
  ansible.builtin.dnf:
    name:
      - "@nvidia-driver:latest-dkms"
  notify:
    - Reboot system
  when: not dry_run

- name: Fetch CUDA repository
  ansible.builtin.get_url:
    dest: /etc/yum.repos.d/cuda-rhel{{ ansible_distribution_major_version }}.repo
    url: https://developer.download.nvidia.com/compute/cuda/repos/rhel{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/cuda-rhel{{ ansible_distribution_major_version }}.repo
    mode: "0644"
    owner: root
    group: root
  when: not dry_run and library_version

- name: Install CUDA
  when: not dry_run and library_version
  block:
    - name: Install CUDA
      no_log: true
      ansible.builtin.dnf:
        name:
          - cuda-{{ library_version | replace('.', '-') }}
  rescue:
    - name: Log error
      ansible.builtin.debug:
        msg: "WARNING Could not install CUDA {{ library_version }}"
  when: not dry_run and library_version
