---
- name: Set host facts
  ansible.builtin.set_fact:
    os_vendor: rhel
    os_version: "{{ ansible_distribution_version }}"
    regex: "amdgpu-install-[0-9\\.]+-1.el[0-9].noarch.rpm"

- name: Find RPM
  ansible.builtin.import_tasks:
    file: "{{ gpu_install_vendor }}/pre_download/fetch_filename.yml"
