on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install ansible-lint
        run: pip3 install ansible-lint
      
      - name: Check lint rules
        run: ansible-lint